In [19]:
import numpy as np
import pandas as pd
import sklearn as sk
from sklearn.preprocessing import LabelBinarizer

df = pd.read_csv('housing.csv')
print(df['ocean_proximity'].unique())
print(df.select_dtypes(exclude=[np.number]).values)

label = LabelBinarizer()
a = label.fit(df.select_dtypes(exclude=[np.number]).values)
label.classes_
b = label.transform(df.select_dtypes(exclude=[np.number]).values)

print(a,b)

['INLAND' '<1H OCEAN' 'NEAR BAY' 'NEAR OCEAN' 'ISLAND']
[['INLAND']
 ['INLAND']
 ['<1H OCEAN']
 ...
 ['<1H OCEAN']
 ['NEAR OCEAN']
 ['NEAR OCEAN']]
LabelBinarizer() [[0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 ...
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]]
